app/dashboard/urls.py
from django.urls import path
from . import views

app_name = "dashboard"

urlpatterns = [
    path("dashboard/", views.dashboard, name="dashboard"),
    path("api/lunarphase/", views.moon_data, name="moon_data"),
]

app/lunar_phase/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from dashboard import urls as dashboard_urls
from django.views.generic import RedirectView

urlpatterns = [
    path('', RedirectView.as_view(url='/login')),
    path('login/', auth_views.LoginView.as_view(template_name='login.html', redirect_authenticated_user=True), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('admin/', admin.site.urls),
    path('', include(dashboard_urls, namespace="dashboard"))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app/dashboard/models.py
from django.db import models

# Create your models here.

app/dashboard/views.py
from django.contrib.auth.decorators import login_required

from datetime import date
from django.shortcuts import render
from django.http import JsonResponse, Http404
from lunar_phase.custom_decorator import logged_in_or_basicauth


# Create your views here.
@login_required
def dashboard(request):
    """
        Dashboard view renders the HTML, CSS and Javscript required to show the current day moon phase,
        It internally makes a call to the moon data api to fetch the required data to present on the UI
    """
    if request.method == 'GET':
        return render(request, 'lunar-phase.html')
    else:
        raise Http404


@logged_in_or_basicauth
def moon_data(request):
    """
        The view returns a JSON response with details of the current day moon phase, the date is
        taken from the browser hence the data will be always user timezone set on the browser
        The api calcualtes considering that On 1/6/2000 at 12:24:01, the moon was New.
    """
    today = date.today()

    Y = int(request.GET.get('year', today.strftime("%Y")))
    M = int(request.GET.get('month', today.strftime("%m")))
    D = int(request.GET.get('day', today.strftime("%d")))
    if M in [1, 2]:
        Y -= 1
        M += 12
    A = int(Y / 100)
    B = int(A / 4)
    C = 2 - A + B
    E = int(365.25 * (Y + 4716))
    F = int(30.601 * (M + 1))
    JD = C + D + E + F - 1524.5
    day_since_known_new_moon = JD - 2451549.5
    no_of_new_moons = day_since_known_new_moon // 29.53
    current_cycle_of_the_moon = (day_since_known_new_moon / 29.53) % 1
    number_of_days_into_moon_cycle = current_cycle_of_the_moon * 29.53
    if number_of_days_into_moon_cycle == 0 or number_of_days_into_moon_cycle == 29.53:
        moon_stage = "New"
    elif 0 < number_of_days_into_moon_cycle < 7:
        moon_stage = "Waxing Crescent"
    elif number_of_days_into_moon_cycle == 7:
        moon_stage = "First Quarter"
    elif 7 < number_of_days_into_moon_cycle < 15:
        moon_stage = "Waxing Gibbous"
    elif number_of_days_into_moon_cycle == 15:
        moon_stage = "Full"
    elif 15 < number_of_days_into_moon_cycle < 22:
        moon_stage = "Waning Gibbous"
    elif number_of_days_into_moon_cycle == 7:
        moon_stage = "Last Quarter"
    elif 22 < number_of_days_into_moon_cycle < 29.53:
        moon_stage = "Waning Crescent"

    percentage_of_moon_cycle = round((number_of_days_into_moon_cycle / 29.53) * 100, 2)

    return JsonResponse({
        'day_since_known_new_moon': day_since_known_new_moon, 'current_cycle_of_the_moon': current_cycle_of_the_moon,
        'percentage_of_moon_cycle': percentage_of_moon_cycle, 'no_of_new_moons': no_of_new_moons,
        'moon_stage': moon_stage, 'moon_image': "{}.png".format(moon_stage.lower().replace(" ", "-"))
    })

app/dashboard/templates/lunar-phase.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!-- Page Wrapper -->
<div id="wrapper">
    <!-- Sidebar -->
    <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">
        <!-- Sidebar - Brand -->
        <a class="sidebar-brand d-flex align-items-center justify-content-center" href="#">
            <div class="sidebar-brand-text mx-3">Moon Phases</div>
        </a>
        <!-- Divider -->
        <hr class="sidebar-divider my-0">
        <!-- Nav Item - Dashboard -->
        <li class="nav-item active">
            <a class="nav-link" href="#">
                <i class="fas fa-fw fa-tachometer-alt"></i>
                <span>Dashboard</span></a>
        </li>
    </ul>
    <!-- End of Sidebar -->
    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">
        <!-- Main Content -->
        <div id="content">
            <!-- Topbar -->
            <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">
                <!-- Sidebar Toggle (Topbar) -->
                <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                    <i class="fa fa-bars"></i>
                </button>
                <!-- Topbar Navbar -->
                <ul class="navbar-nav ml-auto">
                    <!-- Nav Item - Search Dropdown (Visible Only XS) -->
                    <li class="nav-item dropdown no-arrow d-sm-none">
                        <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="fas fa-search fa-fw"></i>
                        </a>
                        <!-- Dropdown - Messages -->
                        <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in" aria-labelledby="searchDropdown">
                            <form class="form-inline mr-auto w-100 navbar-search">
                                <div class="input-group">
                                    <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
                                    <div class="input-group-append">
                                        <button class="btn btn-primary" type="button">
                                            <i class="fas fa-search fa-sm"></i>
                                        </button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </li>
                    <div class="topbar-divider d-none d-sm-block"></div>
                    <!-- Nav Item - User Information -->
                    <li class="nav-item dropdown no-arrow">
                        <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{request.user.email}}</span>
                            <img class="img-profile rounded-circle" src="{% static 'img/undraw_profile.svg'%}">
                        </a>
                        <!-- Dropdown - User Information -->
                        <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
                            <a class="dropdown-item" data-toggle="modal" data-target="#logoutModal">
                                <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                                Logout
                            </a>
                        </div>
                    </li>
                </ul>
            </nav>
            <!-- End of Topbar -->
            <!-- Begin Page Content -->
            <div class="container-fluid">
                <!-- Page Heading -->
                <div class="d-sm-flex align-items-center justify-content-between mb-4">
                    <h1 class="h3 mb-0 text-gray-800">Dashboard</h1>
                </div>
                <div class="row">
                    <div class="col-xl-3 col-md-6 mb-4">
                        <div class="card border-left-primary shadow h-100 py-2">
                            <div class="card-body">
                                <div class="row no-gutters align-items-center">
                                    <div class="col mr-2">
                                        <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                                            Days Since Known New Moon</div>
                                        <div class="h5 mb-0 font-weight-bold text-gray-800" id="days-count"></div>
                                    </div>
                                    <div class="col-auto">
                                        <i class="fas fa-calendar fa-2x text-gray-300"></i>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-xl-3 col-md-6 mb-4">
                        <div class="card border-left-success shadow h-100 py-2">
                            <div class="card-body">
                                <div class="row no-gutters align-items-center">
                                    <div class="col mr-2">
                                        <div class="text-xs font-weight-bold text-success text-uppercase mb-1">
                                            N<sup>th</sup> Moon Cycle</div>
                                        <div class="h5 mb-0 font-weight-bold text-gray-800" id="moon-cycle"></div>
                                    </div>
                                    <div class="col-auto">
                                        <i class="fas fa-redo-alt fa-2x text-gray-300"></i>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-xl-3 col-md-6 mb-4">
                        <div class="card border-left-info shadow h-100 py-2">
                            <div class="card-body">
                                <div class="row no-gutters align-items-center">
                                    <div class="col mr-2">
                                        <div class="text-xs font-weight-bold text-info text-uppercase mb-1">Progress of current moon cycle
                                        </div>
                                        <div class="row no-gutters align-items-center">
                                            <div class="col-auto">
                                                <div class="h5 mb-0 mr-3 font-weight-bold text-gray-800" id="cycle-percentage"></div>
                                            </div>
                                            <div class="col">
                                                <div class="progress progress-sm mr-2">
                                                    <div class="progress-bar bg-info" role="progressbar" id="cycle-percentage-css" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100"></div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-auto">
                                        <i class="fas fa-clipboard-list fa-2x text-gray-300"></i>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- Pending Requests Card Example -->
                    <div class="col-xl-3 col-md-6 mb-4">
                        <div class="card border-left-warning shadow h-100 py-2">
                            <div class="card-body">
                                <div class="row no-gutters align-items-center">
                                    <div class="col mr-2">
                                        <div class="text-xs font-weight-bold text-warning text-uppercase mb-1">
                                            Current Stage of the Moon</div>
                                        <div class="h5 mb-0 font-weight-bold text-gray-800" id="moon-stage"></div>
                                    </div>
                                    <div class="col-auto">
                                        <i class="fab fa-quinscape fa-2x text-gray-300"></i>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-12 mb-12">
                        <!-- Illustrations -->
                        <div class="card shadow mb-4">
                            <div class="card-header py-3">
                                <h6 class="m-0 font-weight-bold text-primary">Illustration</h6>
                            </div>
                            <div class="card-body">
                                <div class="text-center">
                                    <img id="moon-img" class="img-fluid px-3 px-sm-4 mt-3 mb-4" style="width: 25rem;" src="{% static 'img/full.png' %}" alt="...">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- /.container-fluid -->
        </div>
        <!-- End of Main Content -->
        <!-- Footer -->
        <footer class="sticky-footer bg-white">
            <div class="container my-auto">
                <div class="copyright text-center my-auto">
                    <span>Copyright &copy; Demo Website 2021</span>
                </div>
            </div>
        </footer>
        <!-- End of Footer -->
    </div>
    <!-- End of Content Wrapper -->
</div>
<!-- End of Page Wrapper -->
<!-- Scroll to Top Button-->
<a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
</a>
<!-- Logout Modal-->
<div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
            <div class="modal-footer">
                <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                <a class="btn btn-primary" href="{% url 'logout' %}">Logout</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}
{% block extrajs %}
<script type="text/javascript">
$(document).ready(function() {
    var d = new Date();

    var csrftoken = jQuery("[name=csrfmiddlewaretoken]").val();

    function csrfSafeMethod(method) {
        // these HTTP methods do not require CSRF protection
        return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
    }

    $.ajaxSetup({
        beforeSend: function(xhr, settings) {
            // if not safe, set csrftoken
            if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                xhr.setRequestHeader("X-CSRFToken", csrftoken);
            }
        }
    });

    $.ajax({
        url: "{% url 'dashboard:moon_data' %}",
        type: "get",
        data: {
            year: d.getFullYear(),
            month: d.getMonth() + 1,
            day: d.getDate()
        },
        success: function(data) {
            console.log(data);
            $('#days-count').html(data.day_since_known_new_moon);
            $('#moon-cycle').html(data.no_of_new_moons + 1);
            $('#cycle-percentage').html(data.percentage_of_moon_cycle + "%");
            $('#cycle-percentage-css').css('width', data.percentage_of_moon_cycle + "%");
            $('#moon-stage').html(data.moon_stage);
            $("#moon-img").attr("src","/static/img/" + data.moon_image);
        }
    });
});
</script>
{% endblock %}

app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Safeex Exercise</title>
    <!-- Custom fonts for this template-->
    <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
    <!-- Custom styles for this template-->
    <link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet">
    {% block extracss %}
    {% endblock %}
</head>

<body>
    {% block content %}
    {% endblock %}
    <!-- Bootstrap core JavaScript-->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    {% block extrajs %}
    {% endblock %}
</body>

</html>

app/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block extracss %}
<style type="text/css">
body {
    background-color: #abb5d5;
}

.bg-login-image {
    background: url("{% static 'img/login.jpg' %}");
    background-position: center;
    background-size: cover;
}
</style>
{% endblock %}
{% block content %}
<div class="container">
    <!-- Outer Row -->
    <div class="row justify-content-center">
        <div class="col-xl-10 col-lg-12 col-md-9">
            <div class="card o-hidden border-0 shadow-lg my-5">
                <div class="card-body p-0">
                    <!-- Nested Row within Card Body -->
                    <div class="row">
                        <div class="col-lg-6 d-none d-lg-block bg-login-image"></div>
                        <div class="col-lg-6">
                            <div class="p-5">
                                <div class="text-center">
                                    <h1 class="h4 text-gray-900 mb-4">Welcome Back!</h1>
                                </div>
                                <form class="user" action="{% url 'login' %}" method="post" role="form">
                                    {% csrf_token %}
                                    <div class="form-group">
                                        <input type="text" name="username" class="form-control form-control-user" id="id_username" aria-describedby="emailHelp" placeholder="Enter Email Address...">
                                    </div>
                                    <div class="form-group">
                                        <input type="password" class="form-control form-control-user" id="id_password" placeholder="Password" name="password">
                                    </div>
                                    {% if form.errors %}
                                    <p>Your username and password didn't match. Please try again.</p>
                                    {% endif %}
                                    <input type="submit" value="Login" class="btn btn-primary btn-user btn-block">
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}